### ISSUE TITLE
Cadastro de usuários

### ISSUE THREAD

**Issue by rafaelvanat** [gestao-auto/gestao-auto-api#5]
Implementar backend do Cadastro de Usuários com API conforme modelo arquitetura (astah).

**Comment by marihellysantini** [comment]
- Centralizado a criação de usuário através da classe "AutenticacaoRest";
- Criado vínculo de usuário e perfil, atribuindo de modo automático o perfil de usuário final na criação do usuário;
- Criado o CRUD e serviços REST de Proprietário;
- Realizada a exclusão de dependências ao remover um usuário.
